name: gps_speedometer_min
description: Minimal GPS speedometer & trip logger for iOS (Flutter)
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

version: 1.2.0+1

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  intl: ^0.19.0
  sensors_plus: ^6.1.2
  wakelock_plus: ^1.2.8
  uni_links: ^0.5.1
  url_launcher: ^6.3.2
  app_tracking_transparency: ^2.0.6+1
  firebase_core: ^4.1.0
  firebase_analytics: ^12.0.1
  quick_actions: ^1.1.0
  http: ^1.2.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geocoding: ^2.1.1
  apple_maps_flutter: ^1.4.0
  share_plus: ^11.1.0
  path: ^1.9.0
  font_awesome_flutter: ^10.9.1
  file_picker: ^10.3.2
  shared_preferences: ^2.5.3
  in_app_purchase: ^3.2.1
  in_app_purchase_storekit: ^0.4.4
  audioplayers: ^6.5.0
  image_gallery_saver: ^2.0.3
  camera: ^0.11.2
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1   # ← 只有版本放在這裡

# ← 這個是「頂層」設定區塊（不要縮到 dev_dependencies 裡）
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
