// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8PVDIbrJ7aVY2TKQ_lHCihxSnitRIBtc',
    appId: '1:234514423237:web:ed136aa8db2214c2dfffac',
    messagingSenderId: '234514423237',
    projectId: 'gpssmeter-6df2e',
    authDomain: 'gpssmeter-6df2e.firebaseapp.com',
    storageBucket: 'gpssmeter-6df2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQFlwgLAc4bE7bN2jUF_0MnBAjsT_bnTc',
    appId: '1:234514423237:android:ed037b8e0a288c4adfffac',
    messagingSenderId: '234514423237',
    projectId: 'gpssmeter-6df2e',
    storageBucket: 'gpssmeter-6df2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFS_8av7Fs4Nq0i0OiVs4uKfq9ZltvE1Y',
    appId: '1:234514423237:ios:89e1b756d37286c8dfffac',
    messagingSenderId: '234514423237',
    projectId: 'gpssmeter-6df2e',
    storageBucket: 'gpssmeter-6df2e.firebasestorage.app',
    iosBundleId: 'com.GPSSmeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFS_8av7Fs4Nq0i0OiVs4uKfq9ZltvE1Y',
    appId: '1:234514423237:ios:26d822acdd01f50fdfffac',
    messagingSenderId: '234514423237',
    projectId: 'gpssmeter-6df2e',
    storageBucket: 'gpssmeter-6df2e.firebasestorage.app',
    iosBundleId: 'com.example.gpsSpeedometerMin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8PVDIbrJ7aVY2TKQ_lHCihxSnitRIBtc',
    appId: '1:234514423237:web:b8b55ea651013298dfffac',
    messagingSenderId: '234514423237',
    projectId: 'gpssmeter-6df2e',
    authDomain: 'gpssmeter-6df2e.firebaseapp.com',
    storageBucket: 'gpssmeter-6df2e.firebasestorage.app',
  );

}